IF %BGT_VAR%
Global("X#ArchibaldSpoken","GLOBAL",0)
CombatCounter(0)
!See([ENEMY])
InMyArea(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("X#ArchibaldSpoken","GLOBAL",1)
MoveToObject(Player1)
END

IF
Global("X#ArchibaldSpoken","GLOBAL",1)
See(Player1)
THEN
RESPONSE #100
Dialogue(Player1)
END

IF %BGT_VAR%
Global("X#ArchibaldSpoken","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("X#ArchibaldSpoken","GLOBAL",3)
EscapeArea()
END
