IF %BGT_VAR%
OR(2)
Global("P#Briel_Stay","GLOBAL",2)
Global("P#Briel_Stay","GLOBAL",3)
THEN
RESPONSE #100
ActionOverride("brielbara", EscapeArea())
END

IF
NumTimesTalkedToGT(0)
RealGlobalTimerExpired("X#BriLostPatience","GLOBAL")
InParty("coran")
Global("P#Briel_Stay","GLOBAL",1)
Global("X#BriFinale","GLOBAL",0)
Range(Player1,10)
THEN
RESPONSE #100
SmallWait(10)
ActionOverride(Player1,FaceObject("Brielbara"))
SmallWait(10)
StartDialogueNoSet(Player1)
END
