/* Jaheira Heals Beador */
IF
True()
THEN RESPONSE #100
CutSceneId("jaheira")
MoveToObject("beador")
Wait(1)
ReallyForceSpell("beador",CLERIC_CURE_LIGHT_WOUNDS)
FadeToColor([40.0],0)
Wait(5)
ActionOverride("beador",Polymorph(CLERIC_MALE_HUMAN))
Wait(1)
SetGlobal("X#JaheiraHealsB","GLOBAL",4)
Wait(1)
FadeFromColor([20.0],0)
Wait(1)
ActionOverride("beador",StartDialogueNoSet(Player1))
EndCutSceneMode()
END
