INCLUDE ~bg1npc/portraits/lib/s9_addpic.tpa~

COPY ~bg1npc/portraits/lib/x#njnpc.tbl~ override
  READ_2DA_ENTRIES_NOW portlist 2
  FOR (i = 1; i < portlist; ++i) BEGIN
    READ_2DA_ENTRY_FORMER portlist i 0 crename
    READ_2DA_ENTRY_FORMER portlist i 1 filename
    SPRINT $portlist("%crename%") "%filename%"
  END
BUT_ONLY

ACTION_PHP_EACH portlist AS crename => filename BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%crename%.cre~ THEN BEGIN
    LAUNCH_ACTION_MACRO ~s9_addpic~
  END
END
