IF %BGT_VAR%
Global("X#ImoenFIRE","GLOBAL",0)
Global("X#ImCuts","%FirewineBridge%",0)
THEN
RESPONSE #100
SetGlobal("X#ImCuts","%FirewineBridge%",1)
CreateCreature("x#cutspy",[1506.786],3)
CreateCreature("x#cutspy",[3327.2111],3)
END

IF %BGT_VAR%
OR(2) 
Global("X#ImoenFIRE","GLOBAL",2)
Global("X#ImoenFIRE","GLOBAL",3)
THEN
RESPONSE #100
IncrementGlobal("X#ImoenFIRE","GLOBAL",1)
ActionOverride("x#cutspy", DestroySelf())
END
