/* DREAM SCRIPT for Yeslick Banter */
IF %BGT_VAR%
RealGlobalTimerExpired("X#DreamTalk","GLOBAL")
Global("X#ImoenYesl1","GLOBAL",0)
InParty(Myself)
!StateCheck(Myself,CD_STATE_NOTVALID)
InParty("yeslick")
!StateCheck("yeslick",CD_STATE_NOTVALID)
CombatCounter(0)
!See([ENEMY])
THEN
RESPONSE #100
SetGlobal("X#ImoenYesl1","GLOBAL",1)
RealSetGlobalTimer("X#DreamTalk","GLOBAL",180)
StartDialogueNoSet("yeslick")
END

