/* Eldoth's attempted seduction */
IF %BGT_VAR%
RealGlobalTimerExpired("X#DreamTalk","GLOBAL")
Global("X#SKEL2","GLOBAL",0)
InParty(Myself)
!StateCheck(Myself,CD_STATE_NOTVALID)
InParty("eldoth")
!StateCheck("eldoth",CD_STATE_NOTVALID)
CombatCounter(0)
!See([ENEMY])
InMyArea("eldoth")
THEN
RESPONSE #100
SetGlobal("X#SKEL2","GLOBAL",1)
RealSetGlobalTimer("X#DreamTalk","GLOBAL",180)
StartDialogueNoSet("eldoth")
END
