IF
True()
THEN RESPONSE #100
CutSceneId("X#CAUTZ")
FadeToColor([20.0],0)
Polymorph(MAGE_FEMALE_ELF)
Wait(3)
PlaySound("%tutu_var%SIRIN03")
Wait(3)
MoveViewPoint([1419.837],VERY_FAST)
CreateCreature("X#DRAG2",[1419.837],5)
Wait(5)
FadeFromColor([20.0],0)
ActionOverride("X#DRAG2",MoveToPoint([1100.1100]))
MoveViewPoint([1227.1123],FAST)
Wait(1)
SetGlobal("X#FightDragon","GLOBAL",6)
ActionOverride("X#DRAG2",StartDialogueNoSet(Player1))
EndCutSceneMode()
END

