IF
      True()
THEN
    RESPONSE #100
	CutSceneId("ajantis")
	ClearAllActions()
	StorePartyLocations()
	FadeToColor([20.0],0)
	Wait(1)
	LeaveAreaLUA("X#CH14","",[900.700],0)
	ActionOverride(Player1,LeaveAreaLUA("X#CH14","",[1024.1072],9))
	MoveViewPoint([1070.905],INSTANT)
	CreateCreature("X#AJDRSI",[1236.1115],5)
	Wait(1)
	FadeFromColor([20.0],0)
	MoveToPoint([1070.905])
	Dialog(Myself)
	EndCutSceneMode()
END

