/* Madrina */

IF
True()
THEN RESPONSE #100
CutSceneId(Player1)
MoveViewObject(Myself,INSTANT)
SmallWait(15)
FadeToColor([20.0],0)
ActionOverride("X#MADR",JumpToPoint([2399.1353]))
ActionOverride(Player1,JumpToPoint([2343.1400]))
ActionOverride("edwin",JumpToPoint([369.189]))
FadeFromColor([20.0],0)
SetGlobal("X#EdwinMadrina","GLOBAL",3)
MoveViewObject(Myself,INSTANT)
ActionOverride("X#MADR",Dialogue(Player1))
EndCutSceneMode()
END
