IF %BGT_VAR%
Global("X#GorionTalkingLetter","GLOBAL",0)
PartyHasItem("%tutu_var%scrl2J")
THEN
RESPONSE #100
SetGlobal("X#GorionTalkingLetter","GLOBAL",1)
RealSetGlobalTimer("X#GorionLetter","GLOBAL",5)
END

IF %BGT_VAR%
Global("X#GorionTalkingLetter","GLOBAL",1)
RealGlobalTimerExpired("X#GorionLetter","GLOBAL")
THEN
RESPONSE #100
SetGlobal("X#GorionTalkingLetter","GLOBAL",2)
CreateCreatureObject("X#GORLET",Player1,0,0,0)
END
