/* Imoen's bedtime story */
IF %BGT_VAR%
RealGlobalTimerExpired("X#DreamTalk","GLOBAL")
Global("X#YEIM1","LOCALS",0)
InParty("%IMOEN_DV%")
!StateCheck("%IMOEN_DV%",CD_STATE_NOTVALID)
InParty(Myself)
!StateCheck(Myself,CD_STATE_NOTVALID)
CombatCounter(0)
!See([ENEMY])
InMyArea("%IMOEN_DV%")
THEN
RESPONSE #100
SetGlobal("X#YEIM1","LOCALS",1)
RealSetGlobalTimer("X#DreamTalk","GLOBAL",180)
StartDialogueNoSet("%IMOEN_DV%")
END
