IF %BGT_VAR%
NumTimesTalkedTo(0)
Range(Player1,10)
Global("X#XanQuest1","GLOBAL",1)
THEN
RESPONSE #100
Dialogue(Player1)
END

IF %BGT_VAR%
NumTimesTalkedToGT(0)
Range(Player1,10)
Global("X#XanQuest1","GLOBAL",7)
PartyHasItem("P#BAG01")
PartyHasItem("P#BAG02")
THEN
RESPONSE #100
Dialogue(Player1)
END

IF %BGT_VAR%
NumTimesTalkedToGT(0)
Range(Player1,10)
Global("X#XanQuest1","GLOBAL",8)
THEN
RESPONSE #100
Wait(5)
Dialogue(Player1)
END


