/* X#LP3R.BAF */
IF
!AreaCheck("%Peldvale%")
See([PC])
Global("X#LP3RExists","GLOBAL",1)
Global("X#TT3Deactivate","GLOBAL",0)
THEN
  RESPONSE #50
  DisplayStringHead(Myself,@0)
  Wait(15)
  RESPONSE #50
  DisplayStringHead(Myself,@1)
  Wait(15)
  RESPONSE #50
  DisplayStringHead(Myself,@2)
  Wait(15)
  RESPONSE #50
  DisplayStringHead(Myself,@3)
  Wait(15)
  RESPONSE #50
  DisplayStringHead(Myself,@4)
  Wait(15)
END
