/* Karris & Party are added to the area */
/* Source X#TQFW0106 */
/* SEBaldursGate_Blade&Stars_L2 */
IF
Global("X#KarrisPlacement","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("X#KarrisPlacement","GLOBAL",1)
CreateCreature("X#KARRIS",[303.186],12)
CreateCreature("X#TQBH1",[203.189],12)
CreateCreature("X#TQBH2",[224.224],12)
CreateCreature("X#TQBH3",[240.247],12)
CreateCreature("X#TQBH4",[255.227],12)
END